services:
  app:
    image: ghcr.io/ansideome/evolvancebackendapp:latest
    container_name: evolvancebackendapp
    restrart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "8000:8000"
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: